name: Build and deploy ASP.NET Framework app to Azure Web App - JaartaakWebaapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build with MSBuild
        run: msbuild /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:OutputPath=./published

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: net-app
          path: ./published

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_48C57DE53B7949E9B2E310049ADC7F9B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8B13DFB7DBE44705BA8FF71ACEE348C8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AE4FA5DB54D94CF190CC3E781A24756B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'JaartaakWebaapp'
          slot-name: 'Production'
          package: .
